package AgendaApp;


/**
* AgendaApp/Agenda.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Quinta-feira, 19 de Setembro de 2013 10h44min54s BRT
*/

public interface Agenda extends AgendaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Agenda
