package AgendaApp;


/**
* AgendaApp/AgendaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Quinta-feira, 19 de Setembro de 2013 10h44min54s BRT
*/

public interface AgendaOperations 
{
  int salvar (String nome, String telefone);
  int atualizar (String nome, String telefone);
  int apagar (String nome);
  String consultar (String nome);
} // interface AgendaOperations
